# Change the necessary values and rename to lis_data.toml
[SERVER]
SERVER_IP = "0.0.0.0"
SERVER_PORT = 5000

[PHILIPPS_HUE]
HUE_BRIDGE_IP = ""
HUE_CLIENT_KEY = ""

[SPOTIFY]
ACCESS_TOKEN = ""
REFRESH_TOKEN = ""
AUTH_CODE = ""

[WEATHER]
OPEN_WEATHERMAP_API_TOKEN = ""
LATITUDE = 0.00
LONGITUDE = 0.00

[CALENDAR]
CALENDAR_URL = ""

[SOUNDPLAYER]
SOUND_TABLE = ""

[SCHEDULING]
SCHEDULED_EVENTS = []
